
resources:
- name: source-code-from-gitlab
  type: git
  source:
    uri: http://golab.live/eddytnk/gowaka-api
    username: ((gitlab_username))
    password: ((gitlab_password))
    branch: master

- name: minio-s3
  type: s3
  source:
    regexp: gowaka-(.*).jar
    endpoint: ((minio_endpoint_url)) # work out how to configure this per-worker
    bucket: ((minio_bucket))
    access_key_id: ((minio_access_key))
    secret_access_key: ((minio_secret_key))
    region_name: ((minio_region_name))
#    disable_ssl: true
    skip_ssl_verification: true

- name: version
  type: semver
  source:
    driver: git
    uri: http://golab.live/eddytnk/gowaka-api
    username: ((gitlab_username))
    password: ((gitlab_password))
    branch: version
    file: version

jobs:
- name: test-and-build
  public: true
  plan:
  - get: source-code-from-gitlab
    trigger: true
  - get: version
    params: {pre: rc}
  - task: run-test-and-build-jar-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: 8
      inputs:
      - name: source-code-from-gitlab
      - name: version
      outputs:
      - name: jar-file
      caches:
      - path: source-code-from-gitlab/.m2
      run:
        path: source-code-from-gitlab/ci/tasks/test-and-build.sh
#      params:
#        S_USERNAME: ((dev_server_username))
#        S_PASSWORD: ((dev_server_password))
#        S_HOST: ((dev_server_ip))
#        M_ENDPOINT: ((minio_endpoint_url)) # work out how to configure this per-worker
#        M_BUCKET: ((minio_bucket))
#        M_KEY_ID: ((minio_access_key))
#        M_SECRET_KEY: ((minio_secret_key))
#        M_REGION_NAME: ((minio_region_name))
  - put: minio-s3
    params:
      file: jar-file/*.jar
  - put: version
    params: { file: version/version }

- name: deploy-dev
  public: true
  plan:
  - get: minio-s3
    passed: [test-and-build]
    trigger: true
  - get: source-code-from-gitlab
  - get: version
  - task: run-deploy-dev-script
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eddytnk/ldc
          tag: latest
      inputs:
      - name: source-code-from-gitlab
      - name: minio-s3
      run:
        path: ./source-code-from-gitlab/ci/tasks/deploy-dev.sh
      params:
        LDC_TARGET: ((ldc_target))
        LDC_USERNAME: ((ldc_username))
        LDC_PASSWORD: ((ldc_password))
        APP_NAME: ((app_name))
        APP_CLIENT_ID: ((app_client_id))
        APP_CLIENT_SECRET: ((app_client_secret))


- name: major
  plan:
  - put: version
    params: {bump: major, pre: rc}

- name: minor
  plan:
  - put: version
    params: {bump: minor, pre: rc}